### ISSUE TITLE
Docs specifying "Direct return mode" should instead say "Direct server return mode"

### ISSUE THREAD

**Issue by Gbd199** [tigera/docs#1715]
https://github.com/tigera/docs/blob/82333455eaf20adfae4861f04ba701d7b7902958/calico/operations/ebpf/enabling-ebpf.mdx?plain=1#L350
https://github.com/tigera/docs/blob/82333455eaf20adfae4861f04ba701d7b7902958/calico-cloud/operations/ebpf/enabling-ebpf.mdx?plain=1#L237
https://github.com/tigera/docs/blob/82333455eaf20adfae4861f04ba701d7b7902958/calico-enterprise/operations/ebpf/enabling-ebpf.mdx?plain=1#L202

**Comment by ctauchen** [comment]
@tomastigera You're more familiar with the terminology here. WDYT?

**Comment by agowa** [comment]
Hi, also noticed this while reading.

The correct term would indeed be DSR (Direct Server Return). **However** that brings us to a follow up question on this part of the docs. Normally DSR doesn't change any L3 (IPv4/IPv6) addresses but solely rewrite the L2 (MAC) addresses (from itself to one of the backend servers) in order to load balance the traffic between servers. It acts more like a ECMP-router with more sophisticated load balancing than a plain old fashion load balancer and is also very efficient because it takes almost no processing and stays (at least in theory) entirely in kernel space without any context switching or copying of the data and may even be offloaded to the NIC (if it has multiple interfaces, or leaves on the same interface again) .
This is also called "Flat based SLB" (Server Load Balancer).

Sometimes this also used more loosely for a specific configuration within an "Anycast SLB", when a 'real router' is not present, software defined networking is simpler to implement (in the given environment), or simply because one wants to add a simple load balancing at the last hop to an otherwise Anycast setup (e.g. when in a globally distributed anycast design with multiple different data centers around the globe, for whatever reason the last internal hop not being ECMP capable itself).    _(Sidenote: Does Calico support true Anycast via BGP? If yes, also with asymetric routing or rerouting within a connection and cause it to land on another pod? Couldn't find this in the docs. Does anyone know by change?)_

As far as I've seen so far (please correct me if I'm wrong) Calico only supports "NAT based SLB", which technically in the strict est view isn't DSR. But then one rightfully may say it is "Flat based SLB" + an additional DNAT. Also this isn't the key factor of DSR, but the asymetric routing is.

=> **Tl;Dr**: DSR == Direct Server Return and it would be grate if anyone could fill in the part about the DNAT being mandatory with Calico and DSR or if the docs are currently just not verbose enough to highlight that it isn't required.



Further readings about this topic for reference of what I just said above:
* https://de.wikipedia.org/wiki/Lastverteilung_(Informatik)#Serverlastverteilung (sorry, this is the German Wikipedia, as that section doesn't appear to have been that verbosely written in the English version).
* https://en.wikipedia.org/wiki/Linux_Virtual_Server

**Comment by tomastigera** [comment]
@ctauchen it should definitely say Direct Server Return (DSR)

**Comment by tomastigera** [comment]
@agowa DSR here is really only for the _return_ path. A backend server is directly responding to the client without backtracking. Say you have a nodeport and you send stuff to nodeA, but the backend is at nodeB your client will get response with nodeA IP but from nodeB.
